# This is a basic workflow that is manually triggered

name: Code Freeze

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      release_version:
        # Friendly description to be shown in the UI instead of 'name'
        description: "Release version (e.g. 1.2.0)"
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

jobs:
  release:
    runs-on: macos-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout develop
        uses: actions/checkout@v4

      - name: Create release branch
        run: |
          RELEASE_BRANCH="release/${{ inputs.release_version }}"
          git checkout -b "$RELEASE_BRANCH"

      - name: Update iOS App version and build number
        run: |
          pwd
          ls
          cd SpaceNews
          echo "$(<"release.xcconfig")"

          BUILD_NUMBER=$GITHUB_RUN_NUMBER
          MARKETING_VERSION=${{ inputs.release_version }}          
          
          sed -i '' \
            -e "s/^MARKETING_VERSION = .*/MARKETING_VERSION = $MARKETING_VERSION/" \
            -e "s/^CURRENT_PROJECT_VERSION = .*/CURRENT_PROJECT_VERSION = $BUILD_NUMBER/" \
            release.xcconfig

          echo "Build number and version updated"
          echo "$(<"release.xcconfig")"

      - name: Commit version bump
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          BUILD_NUMBER=$GITHUB_RUN_NUMBER
          
          git add .
          git commit -m "chore: cut release ${{ inputs.release_version }} ($BUILD_NUMBER)"

      - name: Push release branch
        run: |
          git push origin HEAD
