name: AstroWire CI

on:
  pull_request:
    branches:
      - 'main'

jobs: 
  build_and_test:
    if: github.event_name == 'pull_request'
    name: Build and Test
    runs-on: macos-latest

    environment: Dev
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Certificates and Provisioning Profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}          
          EXPORT_OPTS: ${{secrets.DEV_EXPORT_OPTIONS_PLIST_BASE64 }}
          
        run: |
            # create variables
            CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
            PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
            KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
            EXPORT_OPTS_PATH=$RUNNER_TEMP/ExportOptions.plist

            echo "create variables done"
            
            # import certificate and provisioning profile from secrets
            echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode > "$CERTIFICATE_PATH"
            ls -lh "$CERTIFICATE_PATH"
            echo "certificate exists"
            file "$CERTIFICATE_PATH"
            echo "check file type"
            #openssl pkcs12 -info -in "$CERTIFICATE_PATH"
            #echo "Check PKCS#12 decoding using OpenSSL"
            echo -n "${{ secrets.PROVISIONING_PROFILE_BASE64 }}" | base64 --decode > "$PP_PATH"

            echo "import cert and provisioning profiles done"
            
            # import export options plist
            echo -n "$EXPORT_OPTS" | base64 --decode > "$EXPORT_OPTS_PATH"

            echo "import export options plist done"
            
            # create keychain
            security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
            echo "create keychain done"
            security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
            echo "set keychain done"
            security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
            echo "unlock keychain done"
            
            # import certificates into keychain            
            security import "$CERTIFICATE_PATH" -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k "$KEYCHAIN_PATH"
            echo "import cert and p12 password done"
            security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
            echo "set-key-partition-list done"
            security list-keychain -d user -s "$KEYCHAIN_PATH"
            echo "list-keychain done"

            echo "import certificates into keychain done"
            
            # import provisioning profile
            mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
            cp "$PP_PATH" ~/Library/MobileDevice/Provisioning\ Profiles
            security find-identity -p codesigning -v
            security cms -D -i ~/Library/MobileDevice/Provisioning\ Profiles/build_pp.mobileprovision
            echo "import provisioning profile done"

      - name: Cache SPM Dependencies
        uses: actions/cache@v4
        id: spm-cache
        with:
          path: 
            /Users/runner/Library/Developer/Xcode/DerivedData/**/SourcePackages/checkouts
            .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      
      - name: List available simulators (optional, for debugging)
        run: xcrun simctl list devices available
        
      - name: Build and Test
        run: |
          xcodebuild clean test -project SpaceNews/SpaceNews.xcodeproj -scheme "SpaceNews" -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 17'
